### ISSUE TITLE
fine-tune model with other dataset

### ISSUE THREAD

**Issue by pokemonlover1** [1991viet/very-deep-cnn-pytorch#1]
Hi,
Thanks for this amazing repository. The code is much more concise than similar ones. Btw, I have one question, how could I re-train some of your pre-trained models with my own dataset?
Best,

**Comment by 1991viet** [comment]
Sure!
You could load pre-trained models I provided in the README file, and then continue training with your own dataset. But please keep in mind that whether my trained models helps or not depends on how similar between your dataset and ones I used, as well as the number of classes.
